name: Flutter Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: Android
            build_target: apk
            build_args: --split-per-abi
            artifact_path: build/app/outputs/flutter-apk/app-*.apk
            artifact_name: android-apk

          - os: ubuntu-latest
            target: Linux
            build_target: linux
            artifact_path: build/linux/x64/release/bundle
            artifact_name: linux-release

          - os: ubuntu-latest
            target: Web
            build_target: web
            artifact_path: build/web
            artifact_name: web-release

          - os: macos-latest
            target: iOS
            build_target: ios
            build_args: --no-codesign
            artifact_path: build/ios/iphoneos
            artifact_name: ios-release

          - os: macos-latest
            target: macOS
            build_target: macos
            artifact_path: build/macos/Build/Products/Release
            artifact_name: macos-release

          - os: windows-latest
            target: Windows
            build_target: windows
            artifact_path: build/windows/runner/Release
            artifact_name: windows-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java for Android
        if: matrix.target == 'Android'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Linux dependencies
        if: matrix.target == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Configure Flutter
        run: |
          flutter config --enable-${{ matrix.build_target }}-desktop
        if: matrix.target == 'Linux' || matrix.target == 'Windows' || matrix.target == 'macOS'

      - name: Get dependencies
        run: flutter pub get

      - name: Build ${{ matrix.target }}
        run: flutter build ${{ matrix.build_target }} ${{ matrix.build_args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
          retention-days: 7

