name: Flutter Multiplatform Test Builds

on:
  push:
    branches:
      - main
  release:
     types: [created, published, prereleased]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      # Build single APK
      - run: flutter build apk --release
      # Build split APKs
      - run: flutter build apk --split-per-abi --release
      - name: Create Android artifacts
        run: |
          # Check for single APK
          if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "Single APK found"
          else
            echo "Single APK not found, creating placeholder"
            mkdir -p build/app/outputs/flutter-apk
            echo "Android build failed to produce APK" > build/app/outputs/flutter-apk/app-release.apk
          fi
          
          # Check for split APKs
          if [ -f "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk" ] || \
             [ -f "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" ] || \
             [ -f "build/app/outputs/flutter-apk/app-x86_64-release.apk" ]; then
            echo "Split APKs found"
            # Create a zip of all split APKs
            cd build/app/outputs/flutter-apk
            zip split-apks.zip *-release.apk
            cd ../../../..
          else
            echo "Split APKs not found, creating placeholder"
            echo "Android build failed to produce split APKs" > build/app/outputs/flutter-apk/split-apks.zip
          fi
      # Upload single APK
      - uses: actions/upload-artifact@v4
        with:
          name: android-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
        if: always()
      # Upload split APKs
      - uses: actions/upload-artifact@v4
        with:
          name: android-split-apks.zip
          path: build/app/outputs/flutter-apk/split-apks.zip
        if: always()

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - name: Build iOS release
        run: |
          flutter clean
          flutter build ios --release --no-codesign
      - name: Debug iOS build artifacts
        run: |
          echo "Listing build directory contents:"
          ls -la build/
          if [ -d "build/ios" ]; then
            echo "iOS build directory contents:"
            ls -la build/ios/
            echo "Searching for app bundles:"
            find build -name "*.app" -type d
          fi
      - name: Create iOS artifact
        run: |
          # Create a zip file with whatever we have in the build directory
          cd build
          if [ -d "ios" ]; then
            zip -r ios-artifact.zip ios
            echo "Created iOS artifact from build output"
          else
            # Create a minimal artifact indicating the build issue
            echo "iOS build did not produce expected output" > ios-artifact.zip
            echo "Created placeholder artifact"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios-artifact.zip
        if: always()

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build web --release
      - name: Create Web artifact
        run: |
          if [ -d "build/web" ]; then
            echo "Web build found, creating zip"
            zip -r web.zip build/web
          else
            echo "Web build not found, creating placeholder"
            echo "Web build failed to produce output" > web.zip
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: web-release.zip
          path: web.zip
        if: always()

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Build Windows App
        run: |
          choco install visualstudio2022buildtools -y  # Install required tools
          choco install innosetup -y  # Install Inno Setup
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release
          
          # Wait for file system and verify build
      - name: Create Installer
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5
          
          Write-Host "Verifying build output:"
          cmd /c dir /s /b "build\windows\runner\Release\*.exe"
          
          $BUILD_DIR = "build\windows\runner\Release"
          Write-Host "Checking build directory using different methods:"
          
          Write-Host "1. Using Test-Path with relative path:"
          if (Test-Path $BUILD_DIR) {
              Write-Host "Directory exists (relative path)"
              Get-ChildItem $BUILD_DIR
          }
          
          Write-Host "2. Using Test-Path with full path:"
          $FULL_PATH = Join-Path $PWD $BUILD_DIR
          Write-Host "Full path: $FULL_PATH"
          if (Test-Path $FULL_PATH) {
              Write-Host "Directory exists (full path)"
              Get-ChildItem $FULL_PATH
          }
          
          Write-Host "3. Using CMD DIR command:"
          cmd /c dir /s /b "$FULL_PATH"
          
          # Create Inno Setup script
          $APP_NAME = "Flutter Todo List"
          $APP_VERSION = "1.0.0"
          $PUBLISHER = "Your Company Name"
          
          # Get absolute path to build directory
          $SOURCE_DIR = Join-Path $PWD "build\windows\runner\Release"
          $SOURCE_DIR = [System.IO.Path]::GetFullPath($SOURCE_DIR)
          
          Write-Host "Preparing Inno Setup with source directory: $SOURCE_DIR"
          
          # Verify build files exist
          if (-not (Test-Path "$SOURCE_DIR\flutter_todo_list.exe")) {
              Write-Error "Could not find flutter_todo_list.exe in $SOURCE_DIR"
              exit 1
          }
          
          $INNO_SCRIPT = "[Setup]`n"
          $INNO_SCRIPT += "AppId={{6EC7C760-D9E7-4736-A2E5-6DB4C8E0CAA1}`n"
          $INNO_SCRIPT += "AppName=$APP_NAME`n"
          $INNO_SCRIPT += "AppVersion=$APP_VERSION`n"
          $INNO_SCRIPT += "AppVerName=$APP_NAME $APP_VERSION`n"
          $INNO_SCRIPT += "AppPublisher=$PUBLISHER`n"
          $INNO_SCRIPT += "AppSupportURL=https://github.com/yourusername/flutter_todo_list`n"
          $INNO_SCRIPT += "DefaultDirName={autopf}\$APP_NAME`n"
          $INNO_SCRIPT += "DefaultGroupName=$APP_NAME`n"
          $INNO_SCRIPT += "OutputDir=build\windows\installer`n"
          $INNO_SCRIPT += "OutputBaseFilename=flutter_todo_list_setup`n"
          $INNO_SCRIPT += "Compression=lzma`n"
          $INNO_SCRIPT += "SolidCompression=yes`n"
          $INNO_SCRIPT += "UninstallDisplayIcon={app}\flutter_todo_list.exe`n"
          $INNO_SCRIPT += "MinVersion=6.0`n"
          $INNO_SCRIPT += "WorkingDir={app}`n"
          $INNO_SCRIPT += "PrivilegesRequired=lowest`n"
          $INNO_SCRIPT += "DisableProgramGroupPage=yes`n"
          $INNO_SCRIPT += "CloseApplications=force`n"
          $INNO_SCRIPT += "WizardStyle=modern`n"
          $INNO_SCRIPT += "SetupIconFile=windows\runner\resources\app_icon.ico`n"
          $INNO_SCRIPT += "LicenseFile=LICENSE`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[Languages]`n"
          $INNO_SCRIPT += "Name: `"english`"; MessagesFile: `"compiler:Default.isl`"`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[Messages]`n"
          $INNO_SCRIPT += "WelcomeLabel2=This will install [name] on your computer.%n%nIt is recommended that you close all other applications before continuing.`n"
          $INNO_SCRIPT += "FinishedLabel=Setup has finished installing [name] on your computer. The application may be launched by selecting the installed shortcuts.`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[Files]`n"
          $INNO_SCRIPT += "Source: `"$($SOURCE_DIR -replace '\\','\\\\')\*`"; DestDir: `"{app}`"; Flags: ignoreversion recursesubdirs createallsubdirs`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[Icons]`n"
          $INNO_SCRIPT += "Name: `"{group}\$APP_NAME`"; Filename: `"{app}\flutter_todo_list.exe`"`n"
          $INNO_SCRIPT += "Name: `"{autodesktop}\$APP_NAME`"; Filename: `"{app}\flutter_todo_list.exe`"`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[Run]`n"
          $INNO_SCRIPT += "Filename: `"{app}\flutter_todo_list.exe`"; Description: `"Launch Flutter Todo List now`"; Flags: postinstall nowait skipifsilent`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[UninstallRun]`n"
          $INNO_SCRIPT += "Filename: `"taskkill.exe`"; Parameters: `"/F /IM flutter_todo_list.exe`"; Flags: runhidden`n"
          $INNO_SCRIPT += "`n"
          $INNO_SCRIPT += "[UninstallDelete]`n"
          $INNO_SCRIPT += "Type: filesandordirs; Name: `"{app}`"`n"
          
          $INNO_SCRIPT | Out-File -FilePath "installer_script.iss" -Encoding UTF8
          
          # Compile installer
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer_script.iss
      - name: Debug Windows build artifacts
        run: |
          Write-Host "Listing build directory contents:"
          if (Test-Path "build") {
            Get-ChildItem -Path "build" -Force -Directory | ForEach-Object { 
              Write-Host "Directory: $_"
              Get-ChildItem -Path "$_" -Recurse -Force
            }
          } else {
            Write-Host "Build directory not found"
          }
          
          # Search for the exe file regardless of path
          Write-Host "Searching for .exe files:"
          $exeFiles = Get-ChildItem -Path . -Include "*.exe" -File -Recurse -ErrorAction SilentlyContinue
          foreach ($file in $exeFiles) {
            Write-Host "Found EXE: $($file.FullName)"
          }
        shell: pwsh
      - name: Create Windows artifacts
        run: |
          # Create zip package of raw build files
          $exeFile = Get-ChildItem -Path . -Include "flutter_todo_list.exe" -File -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if ($exeFile) {
            Write-Host "Found Windows exe file at: $($exeFile.FullName)"
            $exeDir = Split-Path -Parent $exeFile.FullName
            
            # Create zip of raw build files
            Write-Host "Creating standalone Windows package with all required files"
            $tempDir = "windows-package"
            New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
            Copy-Item -Path "$exeDir\*" -Destination $tempDir -Recurse
            Compress-Archive -Path "$tempDir\*" -DestinationPath windows.zip -Force
            Write-Host "Successfully created Windows zip artifact"
          } else {
            Write-Host "Windows executable not found, creating empty zip artifact"
            Set-Content -Path windows.zip -Value "Windows build did not produce expected .exe file"
          }
          
          # Check for Inno Setup installer
          if (Test-Path "build\windows\installer\flutter_todo_list_setup.exe") {
            Write-Host "Inno Setup installer created successfully"
          } else {
            Write-Host "Inno Setup installer not found, creating empty file"
            New-Item -Path "build\windows\installer" -ItemType Directory -Force | Out-Null
            Set-Content -Path "build\windows\installer\flutter_todo_list_setup.exe" -Value "Installer creation failed"
          }
        shell: pwsh
      
      # Upload zip artifact
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release.zip
          path: windows.zip
        if: always()
      
      # Upload installer artifact
      - uses: actions/upload-artifact@v4
        with:
          name: windows-installer.exe
          path: build/windows/installer/flutter_todo_list_setup.exe
        if: always()

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build macos --release
      - name: Create macOS artifact
        run: |
          if [ -d "build/macos/Build/Products/Release" ]; then
            echo "macOS build found, creating zip"
            APP_FILES=$(find build/macos/Build/Products/Release -name "*.app" -type d)
            if [ -n "$APP_FILES" ]; then
              zip -r macos.zip $APP_FILES
              echo "Created macOS zip with app files"
            else
              echo "No .app files found in macOS build"
              echo "macOS build did not produce app files" > macos.zip
            fi
          else
            echo "macOS build directory not found, creating placeholder"
            echo "macOS build failed to produce output" > macos.zip
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release.zip
          path: macos.zip
        if: always()

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - name: Create Linux artifact
        run: |
          if [ -d "build/linux/x64/release/bundle" ]; then
            echo "Linux build found, creating zip"
            zip -r linux.zip build/linux/x64/release/bundle
          else
            echo "Linux build directory not found, creating placeholder"
            echo "Linux build failed to produce output" > linux.zip
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release.zip
          path: linux.zip
        if: always()

  release:
    runs-on: ubuntu-latest
    needs: [android, ios, web, windows, macos, linux]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/**/*.apk
            artifacts/**/*.ipa
            artifacts/**/*.zip
            artifacts/**/*.exe
