name: Flutter Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --split-per-abi
      
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-*.apk
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "Android APK can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Configure Flutter
        run: flutter config --enable-linux-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Linux
        run: flutter build linux
      
      - name: Upload Linux build
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/linux/x64/release/bundle
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "Linux app can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web
      
      - name: Upload Web build
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: build/web
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "Web app can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --no-codesign
      
      - name: Upload iOS build
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/ios/iphoneos
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "iOS app can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Note: iOS apps require code signing for installation on physical devices."

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Configure Flutter
        run: flutter config --enable-macos-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build macOS
        run: flutter build macos
      
      - name: Upload macOS build
        uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: build/macos/Build/Products/Release
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "macOS app can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Configure Flutter
        run: flutter config --enable-windows-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Windows
        run: flutter build windows
      
      - name: Upload Windows build
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release
          retention-days: 7
      
      - name: Create download link
        run: |
          echo "Windows app can be downloaded from the Actions tab, under this workflow run, in the Artifacts section."
          echo "Direct link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

