name: Flutter Multiplatform Build

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Specify your Flutter version
      - run: flutter pub get
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: android-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
    # [[1]][[3]][[7]]

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build ipa --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: ios-release.ipa
          path: build/ios/ipa/*.ipa
    # [[4]][[6]] (Note: Requires Apple Developer certificate setup in secrets)

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-release.zip
          path: web.zip
    # [[4]][[7]]

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build windows --release
      - run: Compress-Archive -Path build\windows\runner\Release -DestinationPath windows.zip
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release.zip
          path: windows.zip
    # [[4]][[6]]

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build macos --release
      - run: zip -r macos.zip build/macos/Build/Products/Release/*.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release.zip
          path: macos.zip
    # [[4]][[6]]

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build linux --release
      - run: zip -r linux.zip build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release.zip
          path: linux.zip
    # [[4]][[8]]

  release:
    runs-on: ubuntu-latest
    needs: [android, ios, web, windows, macos, linux]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/android-release.aab
            artifacts/ios-release.ipa
            artifacts/web-release.zip
            artifacts/windows-release.zip
            artifacts/macos-release.zip
            artifacts/linux-release.zip
    # [[9]][[10]]