name: Flutter Multiplatform Test Builds

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: android-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build ios --debug --no-codesign
      - run: mkdir -p build/ios/ipa
      - run: cp -r build/ios/Debug-iphonesimulator/*.app build/ios/ipa/
      - run: cd build/ios/ipa && zip -r ../ios-simulator.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: build/ios/ios-simulator.zip

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-release.zip
          path: web.zip

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: choco install visualstudio2022buildtools -y  # Install required tools [[5]]
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release
      - run: |
          $releaseDir = "build\windows\runner\Release"
          if (Test-Path $releaseDir) {
            Compress-Archive -Path $releaseDir\* -DestinationPath windows.zip -Force
          } else {
            Write-Error "Release directory not found"
            exit 1
          }
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release.zip
          path: windows.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build macos --release
      - run: zip -r macos.zip build/macos/Build/Products/Release/*.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release.zip
          path: macos.zip

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - run: zip -r linux.zip build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release.zip
          path: linux.zip

  release:
    runs-on: ubuntu-latest
    needs: [android, ios, web, windows, macos, linux]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/**/*.apk
            artifacts/**/*.ipa
            artifacts/**/*.zip