name: Flutter Multiplatform Test Builds

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build apk --debug  # Unsigned debug build [[7]]
      - uses: actions/upload-artifact@v4
        with:
          name: android-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build ipa --simulator  # Unsigned simulator build [[7]]
      - uses: actions/upload-artifact@v4
        with:
          name: ios-simulator.ipa
          path: build/ios/ipa/*.ipa

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-release.zip
          path: web.zip

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build windows --release  # Unsigned EXE [[8]]
      - run: Compress-Archive -Path build\windows\runner\Release -DestinationPath windows.zip
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release.zip
          path: windows.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build macos --release  # Unsigned app bundle [[8]]
      - run: zip -r macos.zip build/macos/Build/Products/Release/*.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release.zip
          path: macos.zip

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build linux --release  # Unsigned Linux binary [[8]]
      - run: zip -r linux.zip build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release.zip
          path: linux.zip

  release:
    runs-on: ubuntu-latest
    needs: [android, ios, web, windows, macos, linux]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/**/*.apk
            artifacts/**/*.ipa
            artifacts/**/*.zip